name: Rafael Laverde
markdown: redcarpet
pygments: true
destination: _site

navigation:
- text: About Me
  url: /#aboutme
- text: Resume
  url: /#resume
- text: Blog
  url: /blog
- text: Contact
  url: /#contact
